# Generated by Django 5.1 on 2024-09-04 13:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0002_alter_produto_table"),
    ]

    operations = [
        migrations.CreateModel(
            name="ConfiguracaoFrete",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("cep_origem", models.CharField(max_length=10)),
                (
                    "desconto_frete",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
                ),
                (
                    "acrescimo_frete",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
                ),
                ("dias_adicionais_entrega", models.IntegerField(default=0)),
            ],
            options={
                "db_table": "configuracao_frete",
            },
        ),
        migrations.CreateModel(
            name="OpcaoFrete",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("id_frete", models.IntegerField(unique=True)),
                ("nome", models.CharField(max_length=255)),
                ("ativo", models.BooleanField(default=False)),
            ],
            options={
                "db_table": "opcao_frete",
            },
        ),
        migrations.AddField(
            model_name="produto",
            name="altura",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=5, null=True
            ),
        ),
        migrations.AddField(
            model_name="produto",
            name="comprimento",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=5, null=True
            ),
        ),
        migrations.AddField(
            model_name="produto",
            name="largura",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=5, null=True
            ),
        ),
        migrations.AddField(
            model_name="produto",
            name="peso",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=5, null=True
            ),
        ),
    ]
