# Generated by Django 5.1 on 2024-09-05 13:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0004_alter_configuracaofrete_acrescimo_frete_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="produto",
            name="tipo_licor",
        ),
        migrations.AlterField(
            model_name="marca",
            name="nome",
            field=models.CharField(max_length=255, null=True),
        ),
    ]
