# Generated by Django 5.1 on 2024-09-07 19:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0006_remove_desconto_tipo_licor"),
    ]

    operations = [
        migrations.CreateModel(
            name="Promocao",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("percentual", models.DecimalField(decimal_places=2, max_digits=5)),
                ("data_inicio", models.DateTimeField()),
                ("data_fim", models.DateTimeField()),
                ("descricao", models.TextField(blank=True, null=True)),
                (
                    "categoria",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="promocao",
                        to="core.categoria",
                    ),
                ),
                (
                    "cliente",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="promocao",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "produto",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="promocao",
                        to="core.produto",
                    ),
                ),
            ],
            options={
                "db_table": "promocao",
            },
        ),
        migrations.DeleteModel(
            name="Desconto",
        ),
    ]
