# Generated by Django 5.1 on 2024-09-07 19:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0007_promocao_delete_desconto"),
    ]

    operations = [
        migrations.DeleteModel(
            name="TipoLicor",
        ),
        migrations.RenameField(
            model_name="promocao",
            old_name="descricao",
            new_name="nome_promo",
        ),
        migrations.RemoveField(
            model_name="promocao",
            name="cliente",
        ),
        migrations.AddField(
            model_name="promocao",
            name="valor_promocao",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
        migrations.AlterField(
            model_name="promocao",
            name="percentual",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=5, null=True
            ),
        ),
    ]
