# Generated by Django 5.1 on 2024-09-08 18:23

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0009_remove_produto_sku"),
    ]

    operations = [
        migrations.AlterField(
            model_name="usuario",
            name="tipo_usuario",
            field=models.CharField(
                choices=[("administrador", "Administrador"), ("cliente", "Cliente")],
                default="administrador",
                max_length=50,
            ),
        ),
        migrations.CreateModel(
            name="Cupom",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("codigo", models.CharField(max_length=50, unique=True)),
                ("descricao", models.TextField(blank=True, null=True)),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("percentual", "Percentual"),
                            ("valor", "Valor Fixo"),
                            ("frete_gratis", "Frete Grátis"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "valor",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                ("data_inicio", models.DateTimeField()),
                ("data_fim", models.DateTimeField()),
                ("ativo", models.BooleanField(default=True)),
                ("uso_maximo", models.IntegerField(blank=True, null=True)),
                ("uso_por_cliente", models.IntegerField(blank=True, null=True)),
                (
                    "valor_minimo_compra",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "valor_maximo_desconto",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                ("categorias", models.ManyToManyField(blank=True, to="core.categoria")),
                (
                    "clientes_exclusivos",
                    models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
                ),
                ("produtos", models.ManyToManyField(blank=True, to="core.produto")),
            ],
        ),
    ]
