# Generated by Django 5.1 on 2024-09-09 18:56

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0010_alter_usuario_tipo_usuario_cupom"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="cupom",
            table="cupom",
        ),
    ]
