# Generated by Django 5.1 on 2024-09-10 13:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0011_alter_cupom_table"),
    ]

    operations = [
        migrations.AddField(
            model_name="produto",
            name="uuid",
            field=models.UUIDField(blank=True, editable=False, null=True, unique=True),
        ),
    ]
