# Generated by Django 5.1 on 2024-09-10 13:32

import uuid
from django.db import migrations, models

def remove_duplicate_uuids(apps, schema_editor):
    Produto = apps.get_model('core', 'Produto')
    seen_uuids = set()
    duplicates = []

    for produto in Produto.objects.all():
        if produto.uuid in seen_uuids:
            duplicates.append(produto)
        else:
            seen_uuids.add(produto.uuid)

    # Regenerar UUIDs únicos para os produtos duplicados
    for produto in duplicates:
        produto.uuid = uuid.uuid4()
        produto.save()

class Migration(migrations.Migration):
    dependencies = [
        ("core", "0012_produto_uuid"),
    ]

    operations = [
        migrations.RunPython(remove_duplicate_uuids),
        migrations.AlterField(
            model_name='produto',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
