# Generated by Django 5.1 on 2024-09-10 17:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0014_imagemproduto_data_criacao_imagemproduto_uuid_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="imagemproduto",
            name="uuid",
            field=models.UUIDField(blank=True, editable=False, null=True, unique=True),
        ),
    ]
