# Generated by Django 5.1 on 2024-10-01 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_alter_carouselimage_imagem'),
    ]

    operations = [
        migrations.CreateModel(
            name='ThemeConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('primary_color', models.CharField(default='#232f3e', max_length=7)),
                ('secondary_color', models.CharField(default='#ffffff', max_length=7)),
                ('background_color', models.CharField(default='#f4f4f4', max_length=7)),
                ('text_color', models.CharField(default='#000000', max_length=7)),
                ('font_family', models.CharField(default='Roboto, Arial, sans-serif', max_length=100)),
            ],
            options={
                'db_table': 'theme_config',
            },
        ),
    ]
