# Generated by Django 5.1 on 2024-10-04 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_themeconfig_border_radius_themeconfig_box_shadow_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='promocao',
            name='produto',
        ),
        migrations.AddField(
            model_name='promocao',
            name='produtos',
            field=models.ManyToManyField(blank=True, related_name='promocoes', to='core.produto'),
        ),
        migrations.RemoveField(
            model_name='promocao',
            name='categoria',
        ),
        migrations.AddField(
            model_name='promocao',
            name='categoria',
            field=models.ManyToManyField(blank=True, related_name='promocoes', to='core.categoria'),
        ),
    ]
