# Generated by Django 5.1 on 2024-10-04 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_remove_promocao_produto_promocao_produtos_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promocao',
            name='categoria',
            field=models.ManyToManyField(blank=True, null=True, related_name='promocoes', to='core.categoria'),
        ),
        migrations.AlterField(
            model_name='promocao',
            name='produtos',
            field=models.ManyToManyField(blank=True, null=True, related_name='promocoes', to='core.produto'),
        ),
    ]
