# Generated by Django 5.1 on 2024-10-08 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_alter_promocao_categoria_alter_promocao_produtos'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='promocao',
            name='categoria',
        ),
        migrations.AddField(
            model_name='promocao',
            name='categorias',
            field=models.ManyToManyField(blank=True, to='core.categoria'),
        ),
        migrations.AlterField(
            model_name='promocao',
            name='produtos',
            field=models.ManyToManyField(blank=True, to='core.produto'),
        ),
    ]
