# Generated by Django 5.1 on 2024-10-08 12:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_remove_promocao_categoria_promocao_categorias_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='produto',
            old_name='categoria',
            new_name='categorias',
        ),
    ]
