# Generated by Django 5.1 on 2024-10-08 12:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_rename_categoria_produto_categorias'),
    ]

    operations = [
        migrations.RenameField(
            model_name='produto',
            old_name='categorias',
            new_name='categoria',
        ),
        migrations.RenameField(
            model_name='promocao',
            old_name='categorias',
            new_name='categoria',
        ),
    ]
