# Generated by Django 5.1 on 2024-10-08 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_rename_categorias_produto_categoria_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promocao',
            name='categoria',
            field=models.ManyToManyField(blank=True, related_name='promocoes', to='core.categoria'),
        ),
    ]
