# Generated by Django 5.1 on 2024-10-11 05:19

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0029_rename_categoria_promocao_categorias"),
    ]

    operations = [
        # migrations.AddField(
        #     model_name="imagemproduto",
        #     name="data_criacao",
        #     field=models.DateTimeField(default=django.utils.timezone.now),
        # ),
        migrations.AlterField(
            model_name="promocao",
            name="produtos",
            field=models.ManyToManyField(
                blank=True, related_name="promocoes", to="core.produto"
            ),
        ),
        migrations.AlterField(
            model_name="usuario",
            name="tipo_usuario",
            field=models.CharField(
                choices=[("administrador", "Administrador"), ("cliente", "Cliente")],
                default="administrador",
                max_length=50,
            ),
        ),
        migrations.CreateModel(
            name="Carrinho",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                ("atualizado_em", models.DateTimeField(auto_now=True)),
                (
                    "usuario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="carrinho",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ItemCarrinho",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantidade", models.PositiveIntegerField(default=1)),
                (
                    "preco_unitario",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                (
                    "carrinho",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="itens",
                        to="core.carrinho",
                    ),
                ),
                (
                    "produto",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.produto"
                    ),
                ),
            ],
        ),
    ]
