# Generated by Django 5.1 on 2024-10-11 20:42

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0031_imagemproduto_data_criacao'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carrinho',
            name='uuid',
        ),
        migrations.AddField(
            model_name='carrinho',
            name='session_id',
            field=models.UUIDField(blank=True, default=uuid.uuid4, editable=False, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='carrinho',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
