# Generated by Django 5.1 on 2024-10-15 00:54

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0031_imagemproduto_data_criacao'),
    ]

    operations = [
        migrations.AddField(
            model_name='carrinho',
            name='session_id',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='produto',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='carrinho',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='carrinho',
            name='uuid',
            field=models.UUIDField(blank=True, default=uuid.uuid4, editable=False, null=True, unique=True),
        ),
        migrations.AlterModelTable(
            name='carrinho',
            table='carrinho',
        ),
        migrations.AlterModelTable(
            name='itemcarrinho',
            table='item_carrinho',
        ),
    ]
