# Generated by Django 5.1 on 2024-10-14 23:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0033_produto_slug'),
    ]

    operations = [
        migrations.RenameField(
            model_name='produto',
            old_name='slug',
            new_name='path',
        ),
    ]
