# Generated by Django 5.1 on 2024-10-15 00:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0034_rename_slug_produto_path'),
    ]

    operations = [
        migrations.RenameField(
            model_name='produto',
            old_name='path',
            new_name='slug',
        ),
    ]
