# Generated by Django 5.1 on 2024-10-15 00:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0035_rename_path_produto_slug'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='carrinho',
            table='carrinho',
        ),
        migrations.AlterModelTable(
            name='itemcarrinho',
            table='item_carrinho',
        ),
    ]
