# Generated by Django 5.1 on 2024-10-15 00:53

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0036_alter_carrinho_table_alter_itemcarrinho_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='carrinho',
            name='uuid',
            field=models.UUIDField(blank=True, default=uuid.uuid4, editable=False, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='carrinho',
            name='session_id',
            field=models.TextField(blank=True, null=True),
        ),
    ]
