from .usuario_serializers import UsuarioSerializer
from .produto_serializers import ProductSerializer, ImagemProdutoSerializer, ProdutoSerializerImport,ImagemProdutoSerializerView, ProdutoSerializer, ProductCupomSerializer, ProdutoSerializerSemDescricao, ProdutoSerializerCarrinho
from .auth_serializers import CustomAdminTokenObtainPairSerializer, CustomClienteTokenObtainPairSerializer
from .frete_serializers import CalculoFreteSerializer, OpcaoFreteSerializer, ConfiguracaoFreteSerializer
from .cupom_serializers import CupomSerializer
from .carousel_serializers import CarouselImageAdminSerializer, CarouselImageClientSerializer
from .theme_serializers import ThemeConfigSerializer
from .categoria_serializers import CategoriaSerializer, CategoriaSerializerNome
from .marca_serializers import MarcaSerializer, MarcaSerializerNome
from .promocao_serializer import PromocaoSerializer
from .item_carrinho_serializer import ItemCarrinhoSerializer, CarrinhoSerializer
