# Generated by Django 5.1 on 2024-09-03 03:46

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0009_marca_tipolicor_remove_produto_categoria_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="produto",
            name="categoria",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="core.categoria",
            ),
        ),
        migrations.AddField(
            model_name="produto",
            name="data_adicionado",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="produto",
            name="data_modificado",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="produto",
            name="descricao",
            field=models.TextField(default="Descrição padrão"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="produto",
            name="marca",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="core.marca",
            ),
        ),
        migrations.AddField(
            model_name="produto",
            name="nome",
            field=models.CharField(default="Nome padrão", max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="produto",
            name="preco_custo",
            field=models.DecimalField(decimal_places=2, default=10, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="produto",
            name="preco_venda",
            field=models.DecimalField(decimal_places=2, default=10, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="produto",
            name="quantidade_estoque",
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="produto",
            name="sku",
            field=models.CharField(default=0, max_length=101, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="produto",
            name="status",
            field=models.CharField(
                choices=[("Ativo", "Ativo"), ("Inativo", "Inativo")],
                default="Ativo",
                max_length=50,
            ),
        ),
        migrations.AddField(
            model_name="produto",
            name="teor_alcoolico",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=4, null=True
            ),
        ),
        migrations.AddField(
            model_name="produto",
            name="tipo_licor",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="core.tipolicor",
            ),
        ),
        migrations.AddField(
            model_name="produto",
            name="volume",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterModelTable(
            name="produto",
            table="produto",
        ),
    ]
