from .user_views import UsuarioCreateView, UsuarioListView, UsuarioDetailView, UsuarioDeleteView
from .product_views import ProdutoViewSet, ProdutosComImagensListView, Products_cupom_ViewSet, ProdutosImagensSemDescricaoListView
from .category_views import CategoriaViewSet, MarcaViewSet
from .token_login_view import CustomTokenObtainPairViewCliente, CustomTokenObtainPairViewAdmin
from .promocao_view import PromocaoSerializer, PromocaoViewSet
from .calcular_frete_view import CalcularFreteView
from .configuracao_frete_view import OpcaoFreteListView, ConfiguracaoFreteView
from .cupom_view import CuponsViewSet, AplicarCupomView
from .imagem_produto_view import ImagemProdutoViewSet, ImagensPorProdutoView
from .imagem_carosel_view import CarouselImageAdminViewSet, CarouselImageListView
from .theme_config_view import ThemeConfigViewSet
from .carrinho_view_set import CarrinhoViewSet