# Generated by Django 5.1 on 2024-09-03 04:44

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="produto",
            table="produto",
        ),
    ]
