# Generated by Django 5.1 on 2024-08-16 00:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='administrador',
            table='administrador',
        ),
        migrations.AlterModelTable(
            name='avaliacao',
            table='avaliacao',
        ),
        migrations.AlterModelTable(
            name='categoria',
            table='categoria',
        ),
        migrations.AlterModelTable(
            name='configuracao',
            table='configuracao',
        ),
        migrations.AlterModelTable(
            name='endereco',
            table='endereco',
        ),
        migrations.AlterModelTable(
            name='historicopedido',
            table='historico_pedido',
        ),
        migrations.AlterModelTable(
            name='imagemproduto',
            table='imagem_produto',
        ),
        migrations.AlterModelTable(
            name='itempedido',
            table='item_pedido',
        ),
        migrations.AlterModelTable(
            name='logacao',
            table='log_acao',
        ),
        migrations.AlterModelTable(
            name='pagamento',
            table='pagamento',
        ),
        migrations.AlterModelTable(
            name='pedido',
            table='pedido',
        ),
        migrations.AlterModelTable(
            name='produto',
            table='produto',
        ),
        migrations.AlterModelTable(
            name='usuario',
            table='usuario',
        ),
    ]
