# Generated by Django 5.1 on 2024-10-15 19:14

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_itemcarrinho_preco_unitario'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemcarrinho',
            name='atualizado_em',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='itemcarrinho',
            name='criado_em',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='usuario',
            name='tipo_usuario',
            field=models.CharField(choices=[('administrador', 'Administrador'), ('cliente', 'Cliente')], default='cliente', max_length=50),
        ),
    ]
