# Generated by Django 5.1 on 2024-08-20 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_administrador_table_alter_avaliacao_table_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='endereco',
            name='cidade',
            field=models.CharField(max_length=200),
        ),
    ]
