# Generated by Django 5.1 on 2024-09-04 14:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0003_configuracaofrete_opcaofrete_produto_altura_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="configuracaofrete",
            name="acrescimo_frete",
            field=models.DecimalField(
                blank=True, decimal_places=2, default=0.0, max_digits=5, null=True
            ),
        ),
        migrations.AlterField(
            model_name="configuracaofrete",
            name="desconto_frete",
            field=models.DecimalField(
                blank=True, decimal_places=2, default=0.0, max_digits=5, null=True
            ),
        ),
        migrations.AlterField(
            model_name="configuracaofrete",
            name="dias_adicionais_entrega",
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
