# Generated by Django 5.1 on 2024-10-17 02:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0003_itemcarrinho_atualizado_em_itemcarrinho_criado_em_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="cupom",
            name="permitir_combinacao_com_promocoes",
            field=models.BooleanField(default=False),
        ),
    ]
