# Generated by Django 5.1 on 2024-08-23 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_endereco_cidade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='sku',
            field=models.CharField(max_length=101, unique=True),
        ),
    ]
