# Generated by Django 5.1 on 2024-10-18 03:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0004_cupom_permitir_combinacao_com_promocoes"),
    ]

    operations = [
        migrations.AlterField(
            model_name="produto",
            name="preco_custo",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
    ]
