# Generated by Django 5.1 on 2024-09-07 18:56

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0005_remove_produto_tipo_licor_alter_marca_nome"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="desconto",
            name="tipo_licor",
        ),
    ]
