# Generated by Django 5.1 on 2024-08-29 18:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_rename_senha_usuario_password_usuario_groups_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imagemproduto',
            name='url_imagem',
        ),
        migrations.AddField(
            model_name='imagemproduto',
            name='imagem',
            field=models.ImageField(blank=True, null=True, upload_to='produtos/'),
        ),
        migrations.AlterField(
            model_name='imagemproduto',
            name='produto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagens', to='core.produto'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='tipo_usuario',
            field=models.CharField(choices=[('administrador', 'Administrador'), ('cliente', 'Cliente')], default='administrador', max_length=50),
        ),
    ]
