# Generated by Django 5.1 on 2024-09-08 15:30

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0008_delete_tipolicor_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="produto",
            name="sku",
        ),
    ]
