# Generated by Django 5.1 on 2024-09-10 17:21

import django.utils.timezone
from django.db import migrations, models
import uuid

def generate_unique_uuids(apps, schema_editor):
    ImagemProduto = apps.get_model('core', 'ImagemProduto')  # Substitua 'core' pelo nome do seu app
    for imagem in ImagemProduto.objects.all():
        if not imagem.uuid:  # Verifica se o UUID já está preenchido
            imagem.uuid = uuid.uuid4()
            imagem.save()

class Migration(migrations.Migration):
    dependencies = [
        ("core", "0013_alter_produto_uuid"),
    ]

    operations = [
        migrations.AddField(
            model_name="imagemproduto",
            name="data_criacao",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name="imagemproduto",
            name="uuid",
            field=models.UUIDField(blank=True, editable=False, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name="imagemproduto",
            name="descricao_imagem",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="imagemproduto",
            name="imagem",
            field=models.ImageField(upload_to="produtos/"),
        ),
        migrations.AddField(
            model_name='imagemproduto',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.RunPython(generate_unique_uuids),  # Executa o script para gerar UUIDs únicos
    ]
