# Generated by Django 5.1 on 2024-09-10 19:22

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0015_alter_imagemproduto_uuid"),
    ]

    operations = [
        migrations.AlterField(
            model_name="imagemproduto",
            name="imagem",
            field=models.ImageField(blank=True, null=True, upload_to="produtos/"),
        ),
        migrations.AlterField(
            model_name="imagemproduto",
            name="uuid",
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
