# Generated by Django 5.1 on 2024-09-30 16:46

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_alter_imagemproduto_imagem_alter_imagemproduto_uuid'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarouselImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('titulo', models.CharField(blank=True, max_length=255, null=True)),
                ('imagem', models.ImageField(upload_to='carousel/')),
                ('ordem', models.PositiveIntegerField(default=0, help_text='Define a ordem em que as imagens aparecem no carrossel.')),
                ('ativo', models.BooleanField(default=True)),
                ('link_url', models.URLField(blank=True, help_text='URL para onde o usuário será redirecionado ao clicar na imagem.', max_length=500, null=True)),
                ('data_inicio', models.DateTimeField(blank=True, help_text='Data e hora de início da exibição.', null=True)),
                ('data_fim', models.DateTimeField(blank=True, help_text='Data e hora de término da exibição.', null=True)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'carousel_image',
            },
        ),
    ]
