# Generated by Django 5.1 on 2024-09-30 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_carouselimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carouselimage',
            name='imagem',
            field=models.ImageField(blank=True, null=True, upload_to='carousel/'),
        ),
    ]
