# Generated by Django 5.1 on 2024-10-02 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_themeconfig'),
    ]

    operations = [
        migrations.AddField(
            model_name='themeconfig',
            name='footer_background_color',
            field=models.CharField(default='#232f3e', max_length=7),
        ),
        migrations.AddField(
            model_name='themeconfig',
            name='footer_text_color',
            field=models.CharField(default='#ffffff', max_length=7),
        ),
        migrations.AddField(
            model_name='themeconfig',
            name='header_background_color',
            field=models.CharField(default='#232f3e', max_length=7),
        ),
        migrations.AlterField(
            model_name='themeconfig',
            name='font_family',
            field=models.CharField(default='Roboto, Arial, sans-serif', max_length=255),
        ),
    ]
