# Generated by Django 5.1 on 2024-10-02 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_usuario_uuid_alter_usuario_tipo_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='themeconfig',
            name='border_radius',
            field=models.CharField(default='4px', max_length=20),
        ),
        migrations.AddField(
            model_name='themeconfig',
            name='box_shadow',
            field=models.CharField(default='none', max_length=255),
        ),
        migrations.AddField(
            model_name='themeconfig',
            name='padding',
            field=models.CharField(default='10px', max_length=20),
        ),
    ]
