# Generated by Django 5.1 on 2024-10-08 13:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_alter_promocao_categoria'),
    ]

    operations = [
        migrations.RenameField(
            model_name='promocao',
            old_name='categoria',
            new_name='categorias',
        ),
    ]
