# Generated by Django 5.1 on 2024-10-11 05:24

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0030_imagemproduto_data_criacao_alter_promocao_produtos_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="imagemproduto",
            name="data_criacao",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
